spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo_db
    username: postgres
    password: samuelmbp123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    # shows sql query in terminal
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
